import random

def startGame(attempts):
    exitFlag = False
    
    if(type(attempts) == int):
        
        numberToGuess = random.randint(1, 100)
        while attempts != 0:
            print(f"You have {attempts} remaining to guess the number")
            guessedNumber = int(input("Make a guess:"))
            
            if guessedNumber > numberToGuess or guessedNumber < numberToGuess:
                attempts = checkGuess(guessedNumber, numberToGuess, attempts)
            else:
                break
        
        if(attempts != 0 and guessedNumber == numberToGuess):
            print(f"Congratulations! {guessedNumber} was the number!")
        else:
           print("You lost...")         
    else:
        return

def checkGuess(guess, answer, attempts):
    """Function that takes in the number guessed by the player, the answer
    generated and the number of attempts, conftronts the guess with the answer
    and decreases the number of attempts.

    Args:
        guess (int): The number guessed by the player
        answer (int): The answer generated by randint()
        attempts (int): The number of attempts remaining

    Returns:
        int: decrease the attepts by 1
    """
    
    if guess > answer:
        print("Too High\nGuess Again")
        
    elif guess < answer:
        print("Too Low\nGuess Again")
    
    return attempts - 1    

def setDifficulty(difficulty):
    if(difficulty == "easy"):
        return 10
    elif(difficulty == "hard"):
        return 5
    else:
        print("Error. Invalid Input")
        return

numberOfAttempts = 0

print("Welcome to the number guessing game!")
print("I'm thinking of a number between 1 and 100")
difficulty = input("Choose a difficulty. Type 'easy' or 'hard': ").lower()

numberOfAttempts = setDifficulty(difficulty)

startGame(numberOfAttempts)